import os
import yaml
from os import listdir
from os.path import isfile, join
import pathlib

SNAKEMAKE_DIR = os.path.dirname(workflow.snakefile)

# Read config from dataset (user can change accordingly)
configfile: "./config.yaml"

def splicemap5(wildcards):
    path = Path(config['splicemap_dir'])
    # __import__("pdb").set_trace()
    return [
        path / 'Cells_Cultured_fibroblasts_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz',
        path / 'Cells_EBV_transformed_lymphocytes_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz'
    ]
    # return [x for x in path.iterdir() if x.is_file() and 'splicemap_psi5' in str(x) and 'Cells_Cultured_fibroblasts' in str(x)]

def splicemap3(wildcards):
    path = Path(config['splicemap_dir'])
    return [
        path / 'Cells_Cultured_fibroblasts_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz',
        path / 'Cells_EBV_transformed_lymphocytes_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz'
    ]
    # return [x for x in path.iterdir() if x.is_file() and 'splicemap_psi3' in str(x) and 'Cells_Cultured_fibroblasts' in str(x)]


rule all:
    input:
        config['splicing_pred']['spliceai_vcf']
        # config['splicing_pred']['mmsplice_splicemap']
        # config['clinvar']['vcf_subset']
        # config['clinvar']['vcf'],
        # config['fasta']['file'],
        # config['splicing_pred']['mmsplice_splicemap']


rule download_clinvar:
    params:
        url = config['clinvar']['url']
    output:
        config['clinvar']['vcf'],
        config['clinvar']['vcf_tbi']
    run:
        shell('wget {params.url}')
        shell('wget {params.url}.tbi')


rule subset_vcf:
    input:
        config['clinvar']['vcf']
    params:
        region = config['clinvar']['region']
    output:
        config['clinvar']['vcf_subset']
    run:
        vcf_ungziped = output[0].replace('.gz', '')
        shell('tabix -h {input} {params.region} > {vcf_ungziped}')
        shell('bgzip {vcf_ungziped}')
        shell('tabix -p vcf {output}')


rule download_human_fasta:
    params:
        config['fasta']['url']
    output:
        config['fasta']['file']
    shell:
        "wget -O - {params} | gunzip -c > {output}"


rule mmsplice_splicemap:
    input:
        vcf = config['clinvar']['vcf_subset'],
        fasta = config['fasta']['file'],
        splicemap_5 = splicemap5,
        splicemap_3 = splicemap3,
    output:
        result = config['splicing_pred']['mmsplice_splicemap']
    script:
        "./mmsplice_splicemap.py"


rule spliceai:
    input:
        vcf = config['clinvar']['vcf_subset'],
        fasta = config['fasta']['file']
    params:
        genome = 'grch38'
    output:
        result = config['splicing_pred']['spliceai_vcf']
    shell:
        'spliceai -I {input.vcf} -O {output.result} -R {input.fasta} -A {params.genome}'
        # 'cat {input.vcf} | spliceai -R {input.fasta} -A {params.genome} > {output.result}'
# rule spliceai:
#     input:
#         vcf = config['vcf'],
#         db = config_precomputed['spliceai']['db'].format(
#             genome=config['genome']),
#         fasta = config['fasta'],
#     params:
#         lookup_only = config['spliceai']['lookup_only'],
#         genome = config['genome'],
#     output:
#         result = directory(config['splicing_pred']['spliceai'])
#     script:
#         "./spliceai.py"

    
# rule absplice_dna:
#     input:
#         mmsplice_splicemap = config['splicing_pred']['mmsplice_splicemap']],
#         spliceai = config['splicing_pred']['spliceai'],
#     output:
#         absplice_dna = directory(config['splicing_pred']['absplice'])
#     script:
#         "./absplice_dna.py"