import os
import yaml
from os import listdir
from os.path import isfile, join
import pathlib

SNAKEMAKE_DIR = os.path.dirname(workflow.snakefile)

configfile: "./config.yaml"

def splicemap5(wildcards):
    path = Path(config['splicemap_dir'])
    splicemaps =  [
        path / 'Testis_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz',
        path / 'Cells_Cultured_fibroblasts_splicemap_psi5_method=kn_event_filter=median_cutoff.csv.gz',
    ]
    splicemaps = [str(x) for x in splicemaps]
    return splicemaps

def splicemap3(wildcards):
    path = Path(config['splicemap_dir'])
    splicemaps =  [
        path / 'Testis_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz',
        path / 'Cells_Cultured_fibroblasts_splicemap_psi3_method=kn_event_filter=median_cutoff.csv.gz',
    ]
    splicemaps = [str(x) for x in splicemaps]
    return splicemaps


rule all:
    input:
        config['splicing_pred']['absplice_dna'],
        

rule download_human_fasta:
    params:
        config['fasta']['url']
    output:
        config['fasta']['file']
    shell:
        "wget -O - {params} | gunzip -c > {output}"


rule download_splicemaps:
    output:
        directory(config['splicemap_dir'])
    shell:
        "splicemap_download --version gtex_v8 --splicemap_path {output}"
            
        
rule mmsplice_splicemap:
    input:
        vcf = config['vcf'],
        fasta = config['fasta']['file'],
        splicemap_dir = config['splicemap_dir']
    params:
        splicemap_5 = splicemap5,
        splicemap_3 = splicemap3,
    output:
        result = config['splicing_pred']['mmsplice_splicemap']
    script:
        "./mmsplice_splicemap.py"


rule spliceai:
    input:
        vcf = config['vcf'],
        fasta = config['fasta']['file']
    params:
        genome = 'grch38'
    output:
        result = config['splicing_pred']['spliceai_vcf']
    shell:
        'spliceai -I {input.vcf} -O {output.result} -R {input.fasta} -A {params.genome}'

    
rule absplice_dna:
    input:
        mmsplice_splicemap = config['splicing_pred']['mmsplice_splicemap'],
        spliceai = config['splicing_pred']['spliceai_vcf'],
    output:
        absplice_dna = config['splicing_pred']['absplice_dna']
    script:
        "./absplice_dna.py"