name: absplice
channels:
  - conda-forge
dependencies:
  - python==3.8
  - cython
  - tensorflow
  - pytest
  - setuptools
  - scipy
  - pandas
  - tqdm
  - click
  - pip
  - pyarrow
  - onnx
  - onnxruntime
  - pandas
  # needed for splicemap
  - seaborn
  - scikit-learn
  - bioconda::pyfaidx
  - bioconda::pyranges>=0.0.71
  - bioconda::cyvcf2
  - bioconda::tabix
  - bioconda::snakemake
  - bioconda::spliceai
  - bioconda::kipoiseq>=0.7
  - deepdiff
  - pip:
    - mmsplice
#    - interpret
    - git+https://github.com/gagneurlab/splicemap.git