version: 2.1
jobs:
  build:
    docker:
      - image: condaforge/mambaforge:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mamba env create -f environment.yaml
            source activate absplice
            pip install -e .
      - run:
          name: Run tests
          command: pytest tests/
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
