version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda env create -f environment.yaml
            conda activate absplice
            pip install -e .
      - run:
          name: Run tests
          command: pytest
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
