version: 2.1
jobs:
  build:
    docker:
      - image: condaforge/mambaforge:latest
    steps:
      - checkout
      - run:
          name: Install essential build tools
          command: |
            apt-get update
            apt-get install -y build-essential
      - run:
          name: Create environment for AbSplice
          command: |
            mamba env create -f environment.yaml
            source activate absplice
            pip install -e .
      - run:
          name: Run tests
          command: |
            source activate absplice
            pytest tests/
      - run:
          name: Run example
          command: |
            source activate absplice
            cd example/workflow
            python -m snakemake -j 1 --use-conda --cores 10
      - run:
          name: Create environment for rocksdb lookup
          command: |
            mamba env create -f example/envs/environment_spliceai_rocksdb.yaml
            source activate spliceai-rocksdb
workflows:
  version: 2
  build-and-test:
    jobs:
      - build