version: 2.1
jobs:
  build:
    docker:
      - image: condaforge/mambaforge:latest
    steps:
      - checkout
      - run:
          name: Install essential build tools
          command: |
            apt-get update
            apt-get install -y build-essential
      - run:
          name: Install dependencies
          command: |
            mamba env create -f environment.yaml
            source activate absplice
            pip install -e .
      - run:
          name: Run tests
          command: |
            source activate absplice
            pytest tests/
      - run:
          name: Run example
          command: |
            source activate absplice
            python -m snakemake -s example/Snakefile -j 1 --use-conda
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
